### ISSUE TITLE
Не хватает кнопки «развернуть всё»

### ISSUE THREAD

**Issue by roboxdev** [phenomen/dnd5e-ru-ref#4]
Спасибо за справочник, очень удобный!

Есть одна небольшая трудность: если хочется воспользоваться поиском по странице, приходится сперва развернуть каждый спойлер. 

Хотелось бы кнопку «развернуть всё»

**Comment by phenomen** [comment]
Добавлено в https://github.com/phenomen/dnd5e-ru-ref/commit/0b81b9f614e45814c4b9bd48ba99dc443e3ecf50
